name: "Ensure previous version is tagged"

on:
  pull_request:
    branches:
      - master
      - main
jobs:
  check-previous-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Check if previous commit is tagged
        run: |
          # Récupérer le dernier commit sur master
          PREVIOUS_COMMIT=$(git rev-parse origin/master^)
          # Vérifier si ce commit est tagué
          if [ -z "$(git tag --points-at $PREVIOUS_COMMIT)" ]; then
            echo "Error: The previous commit on master is not tagged!"
            exit 1
          fi